name:                notional-machines
version:             0.1.0.0
github:              "luceresearchlab/structured-notional-machines"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LuCEresearchlab/structured-notional-machines#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- mtl
- hedgehog
- prettyprinter
- pretty-simple
- repline
- colour
- diagrams-lib
- diagrams-svg
- diagrams-rasterific
- diagrams-contrib
- diagrams-input
- palette
- bytestring
- raw-strings-qq
- split

library:
  source-dirs: src

executables:
  notional-machines-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notional-machines

tests:
  notional-machines-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notional-machines
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - hedgehog
